/**
 * PanelIQ Dev 3 Assessment Fixtures
 * Strictly adheres to backend contracts, seed questions (backend-developer.questions.json),
 * and PRD Section 14.4 requirements.
 */

export const MOCK_REPORTS = {
  'ses_demo_backend_01': {
    id: 'ses_demo_backend_01',
    sessionId: 'ses_demo_backend_01',
    status: 'draft', // 'draft' | 'ai_draft' | 'reviewed' | 'human_reviewed' | 'pending'
    candidate: {
      id: 'usr_candidate_01',
      displayName: 'Alex Chen',
      email: 'alex.chen@example.com',
      avatarUrl: null,
      domain: 'computer_science',
      experienceLevel: 'junior',
      targetRole: 'Backend Developer',
    },
    interview: {
      startedAt: '2026-09-27T10:15:00.000Z',
      completedAt: '2026-09-27T10:48:30.000Z',
      durationMinutes: 33,
      mode: 'Standard Boardroom (3 Panelists)',
      totalTurns: 8,
      answeredCount: 8,
    },
    scores: {
      composite: 3.4,
      max: 4.0,
      percentile: 84,
      criteria: [
        {
          id: 'correctness',
          label: 'Technical Correctness',
          score: 3.4,
          max: 4.0,
          weight: 0.35,
          colorVariant: 'accent',
          description: 'Accuracy of algorithmic patterns, database locking semantics, and API status codes.',
        },
        {
          id: 'reasoning',
          label: 'Architectural Reasoning',
          score: 3.6,
          max: 4.0,
          weight: 0.25,
          colorVariant: 'primary',
          description: 'Coherent defense of database choices and isolation level trade-offs under scale.',
        },
        {
          id: 'relevance',
          label: 'Direct Relevance',
          score: 3.8,
          max: 4.0,
          weight: 0.20,
          colorVariant: 'success',
          description: 'Directly addresses prompt constraints without evading edge cases or over-engineering.',
        },
        {
          id: 'tradeoffs',
          label: 'Trade-offs & Application',
          score: 2.9,
          max: 4.0,
          weight: 0.20,
          colorVariant: 'warning',
          description: 'Evaluation of operational complexity, payment retry races, and deadline triage.',
        },
      ],
    },
    coverage: {
      totalPlanned: 8,
      totalEvaluated: 8,
      coveragePercent: 100,
      domains: [
        { name: 'APIs & Contracts', weight: 0.25, score: 3.8, questionsCount: 2, status: 'proficient' },
        { name: 'Databases & Indexing', weight: 0.25, score: 3.5, questionsCount: 2, status: 'proficient' },
        { name: 'Concurrency & Locking', weight: 0.25, score: 2.8, questionsCount: 2, status: 'needs_retry' },
        { name: 'Project Trade-offs & Triage', weight: 0.25, score: 3.7, questionsCount: 2, status: 'mastered' },
      ],
    },
    questionQuality: {
      roleRelevance: 3.9,
      levelFit: 3.7,
      clarity: 3.8,
      assessability: 3.6,
      topicCoveragePercent: 94,
      totalPromptsEvaluated: 8,
      recommendations: [
        'The concurrency constraint follow-up effectively tested idempotency under aggressive retries.',
        'Clarify timeout expectations in question #4 to make pessimistic locking comparisons more concrete.',
      ],
      rubricMetrics: [
        {
          dimension: 'Role Relevance',
          score: 3.9,
          description: 'Prompts match real-world junior backend engineer production responsibilities.',
        },
        {
          dimension: 'Level Fit',
          score: 3.7,
          description: 'Calibrated appropriately for junior-to-mid career transition without trick puzzles.',
        },
        {
          dimension: 'Clarity',
          score: 3.8,
          description: 'High semantic clarity with explicit business scenarios and boundary conditions.',
        },
        {
          dimension: 'Assessability',
          score: 3.6,
          description: 'Rubric criteria clearly differentiate surface answers from deep mechanical insight.',
        },
      ],
    },
    turns: [
      {
        turnPosition: 1,
        questionId: 'be-j-intro-project',
        stage: 'icebreaker',
        panelRole: 'chair',
        panelName: 'Dr. Aris Thorne (Panel Chair)',
        prompt: 'Describe a small backend project you built. What did it do, and which part did you personally implement?',
        candidateAnswer: 'I developed an internal book reservation API using Node.js, Express, and PostgreSQL. I implemented user authentication with JWT, designed the database schema with foreign key constraints, and wrote the reservation endpoints with transaction boundaries so multiple users could not hold the last book simultaneously.',
        score: 3.7,
        maxScore: 4.0,
        source: 'AI Evaluator - Calibrated Rubric',
        evidence: {
          excerpt: 'designed the database schema with foreign key constraints, and wrote the reservation endpoints with transaction boundaries',
          criterion: 'Technical Correctness & Clarity',
          explanation: 'Candidate clearly specified their direct contribution, mentioning database transactions and relational integrity without claiming out-of-scope microservices.',
          missingPoints: ['Did not specify how reservation expiration or lease cleanup was handled in the background.'],
        },
        eligibleForRetry: false,
      },
      {
        turnPosition: 2,
        questionId: 'be-j-api-validation',
        stage: 'technical',
        panelRole: 'specialist',
        panelName: 'Elena Rostova (Technical Specialist)',
        prompt: 'You are adding POST /tasks. What would you validate before saving a task, and what response would you send for invalid input?',
        candidateAnswer: 'First, I validate the payload format: ensure title is a non-empty string under 255 characters, priority is an enum [LOW, MEDIUM, HIGH], and dueDate is an ISO-8601 string in the future. For validation failures, I return HTTP 422 Unprocessable Entity with a structured JSON body listing field-level error messages (field, rule, message). If the request is malformed JSON, I return HTTP 400 Bad Request.',
        score: 3.8,
        maxScore: 4.0,
        source: 'AI Evaluator - Calibrated Rubric',
        evidence: {
          excerpt: 'HTTP 422 Unprocessable Entity with a structured JSON body listing field-level error messages (field, rule, message)',
          criterion: 'API Contract Design',
          explanation: 'Excellent distinction between syntax parsing failures (HTTP 400) and semantic validation failures (HTTP 422), conforming to RFC 7807 problem details.',
          missingPoints: ['Could have mentioned authentication/authorization checks before validating heavy payload bodies.'],
        },
        eligibleForRetry: false,
      },
      {
        turnPosition: 3,
        questionId: 'be-j-db-uniqueness',
        stage: 'technical',
        panelRole: 'specialist',
        panelName: 'Elena Rostova (Technical Specialist)',
        prompt: 'Two users try to register the same email almost simultaneously. Why is checking whether the email exists before inserting insufficient, and what would you add?',
        candidateAnswer: 'A SELECT query followed by an INSERT is vulnerable to a Time-of-Check to Time-of-Use (TOCTOU) race condition. Both concurrent requests can execute SELECT at the same instant, see 0 rows, and both proceed to INSERT. To guarantee uniqueness, I must enforce a database-level UNIQUE constraint on the email column. Then, in the application layer, catch the PostgreSQL unique violation error code (23505) and return a friendly 409 Conflict.',
        score: 3.9,
        maxScore: 4.0,
        source: 'AI Evaluator - Calibrated Rubric',
        evidence: {
          excerpt: 'enforce a database-level UNIQUE constraint on the email column. Then, in the application layer, catch the PostgreSQL unique violation error code (23505) and return a friendly 409 Conflict',
          criterion: 'Concurrency & Database Integrity',
          explanation: 'Accurately recognized race window between application queries and delegated authoritative atomicity to the database engine constraint.',
          missingPoints: ['No significant omissions for junior level.'],
        },
        eligibleForRetry: false,
      },
      {
        turnPosition: 4,
        questionId: 'be-j-concurrency-stock',
        stage: 'technical',
        panelRole: 'specialist',
        panelName: 'Elena Rostova (Technical Specialist)',
        prompt: 'An item has one unit left. Two requests both read the stock as one and both place an order. Explain a database approach that prevents selling two units.',
        candidateAnswer: 'We can run the order placement inside an explicit database transaction and use SELECT stock FROM inventory WHERE item_id = 123 FOR UPDATE. This takes an exclusive row-level lock. The second transaction will block until the first commits and reduces stock to zero. Alternatively, we could do UPDATE inventory SET stock = stock - 1 WHERE item_id = 123 AND stock >= 1, checking the affected rows count.',
        score: 3.4,
        maxScore: 4.0,
        source: 'AI Evaluator - Calibrated Rubric',
        evidence: {
          excerpt: 'UPDATE inventory SET stock = stock - 1 WHERE item_id = 123 AND stock >= 1, checking the affected rows count',
          criterion: 'Locking Semantics & Optimistic Patterns',
          explanation: 'Solid identification of both pessimistic row locking (SELECT FOR UPDATE) and atomic conditional updates.',
          missingPoints: ['Did not address lock contention duration or transaction timeout hazards.'],
        },
        eligibleForRetry: false,
      },
      {
        turnPosition: 5,
        questionId: 'be-j-concurrency-constraint',
        stage: 'technical',
        panelRole: 'specialist',
        panelName: 'Elena Rostova (Technical Specialist)',
        prompt: 'How does your stock reservation handle network timeouts when a third-party payment gateway is slow to respond? (Constraint Follow-up: Two identical requests now arrive simultaneously due to aggressive client retries).',
        candidateAnswer: 'If payment times out, we should probably rollback the order or wait for webhook. If two identical requests arrive, we can check if the user has an existing order in the table and reject the second one.',
        score: 2.3,
        maxScore: 4.0,
        source: 'AI Evaluator - Calibrated Rubric',
        evidence: {
          excerpt: 'If two identical requests arrive, we can check if the user has an existing order in the table and reject the second one',
          criterion: 'Distributed Reliability & Idempotency',
          explanation: 'The candidate did not mention Idempotency Keys (e.g. Idempotency-Key header), deduplication tokens, or an explicit pending payment state with a leased lock.',
          missingPoints: [
            'Omitted Idempotency-Key header standard for preventing duplicate charging on client retries.',
            'Failed to specify a two-phase reservation with TTL expiration for pending third-party payment callbacks.',
            'Did not explain how to return the cached authoritative order response to the retried client request.',
          ],
        },
        eligibleForRetry: true,
        targetSkill: 'Idempotent Payment Handling & Retry Deduplication',
      },
      {
        turnPosition: 6,
        questionId: 'be-j-project-deadline',
        stage: 'techno_managerial',
        panelRole: 'evaluator',
        panelName: 'Marcus Vance (Project Evaluator)',
        prompt: 'Your team has one day left. Search filters and reliable task saving are both unfinished. How would you choose scope and communicate the decision?',
        candidateAnswer: 'Data persistence and reliability always take precedence over convenience features. If task saving fails, the product loses user data, which destroys user trust. Search filters can be substituted temporarily with basic sorting or in-memory list rendering. I would immediately message the engineering manager and product lead explaining: 1) why reliable task saving is critical path, 2) proposing to ship basic saving first, and 3) deferring search filters to the next sprint.',
        score: 3.8,
        maxScore: 4.0,
        source: 'AI Evaluator - Calibrated Rubric',
        evidence: {
          excerpt: 'Data persistence and reliability always take precedence over convenience features. If task saving fails, the product loses user data',
          criterion: 'Engineering Triage & Stakeholder Communication',
          explanation: 'Clear prioritization of data integrity over user convenience, paired with proactive stakeholder communication.',
          missingPoints: ['Could have proposed creating a feature flag or stubbing the search UI gracefully.'],
        },
        eligibleForRetry: false,
      },
      {
        turnPosition: 7,
        questionId: 'be-j-project-contract',
        stage: 'techno_managerial',
        panelRole: 'evaluator',
        panelName: 'Marcus Vance (Project Evaluator)',
        prompt: 'A frontend teammate expects dueDate but your API returns deadline. How would you resolve this mismatch and prevent similar integration surprises?',
        candidateAnswer: 'In the immediate term, I would update the API serializer to return both dueDate and deadline (aliasing the field) so neither the existing frontend nor new builds break. Then we can deprecate deadline. To prevent this, I would establish OpenAPI/Swagger contracts stored in a shared repository with automated schema validation in our CI pipeline.',
        score: 3.7,
        maxScore: 4.0,
        source: 'AI Evaluator - Calibrated Rubric',
        evidence: {
          excerpt: 'update the API serializer to return both dueDate and deadline (aliasing the field) so neither the existing frontend nor new builds break',
          criterion: 'Contract Evolution & Backward Compatibility',
          explanation: 'Pragmatic backward compatibility handling through aliasing, combined with a preventative OpenAPI schema-first strategy.',
          missingPoints: ['Did not mention contract testing tools like Pact or TypeScript type generation.'],
        },
        eligibleForRetry: false,
      },
      {
        turnPosition: 8,
        questionId: 'be-j-reflect-improve',
        stage: 'reflection',
        panelRole: 'chair',
        panelName: 'Dr. Aris Thorne (Panel Chair)',
        prompt: 'Which answer today would you improve with another ten minutes, and how would you check whether your revised approach is correct?',
        candidateAnswer: 'I would improve my response on question #5 regarding third-party payment timeouts and retries. I should have explained Idempotency Keys stored with a unique constraint in a Redis or Postgres table to guarantee that multiple mobile retry requests do not double charge. To verify correctness, I would write an automated integration test using Promise.all() to fire 5 identical concurrent requests with the same idempotency key and verify that only one charge is executed while all 5 receive the same order ID.',
        score: 3.9,
        maxScore: 4.0,
        source: 'AI Evaluator - Calibrated Rubric',
        evidence: {
          excerpt: 'write an automated integration test using Promise.all() to fire 5 identical concurrent requests with the same idempotency key and verify that only one charge is executed',
          criterion: 'Self-Correction & Empirical Verification',
          explanation: 'Exceptional reflective insight. Directly acknowledged the previous gap and provided a concrete, testable verification method.',
          missingPoints: ['No significant omissions.'],
        },
        eligibleForRetry: false,
      },
    ],
  },

  'ses_demo_pending_02': {
    id: 'ses_demo_pending_02',
    sessionId: 'ses_demo_pending_02',
    status: 'pending', // NEVER DISPLAY AS ZERO
    candidate: {
      id: 'usr_candidate_02',
      displayName: 'Maya Patel',
      email: 'maya.patel@example.com',
      avatarUrl: null,
      domain: 'computer_science',
      experienceLevel: 'mid',
      targetRole: 'Full Stack Engineer',
    },
    interview: {
      startedAt: '2026-09-27T14:00:00.000Z',
      completedAt: '2026-09-27T14:42:00.000Z',
      durationMinutes: 42,
      mode: 'Senior Technical Boardroom',
      totalTurns: 8,
      answeredCount: 8,
    },
    scores: {
      composite: null, // Nullable when pending
      max: 4.0,
      percentile: null,
      criteria: [
        {
          id: 'correctness',
          label: 'Technical Correctness',
          score: 3.2,
          max: 4.0,
          weight: 0.35,
          colorVariant: 'accent',
          isPending: true,
          description: 'Evaluating transaction isolation anomalies and async queue worker patterns.',
        },
        {
          id: 'reasoning',
          label: 'Architectural Reasoning',
          score: 3.5,
          max: 4.0,
          weight: 0.25,
          colorVariant: 'primary',
          isPending: true,
          description: 'Analyzing distributed cache invalidation rationale.',
        },
        {
          id: 'relevance',
          label: 'Direct Relevance',
          score: 3.7,
          max: 4.0,
          weight: 0.20,
          colorVariant: 'success',
          isPending: true,
          description: 'Validating response adherence to prompt scope.',
        },
        {
          id: 'tradeoffs',
          label: 'Trade-offs & Application',
          score: 3.1,
          max: 4.0,
          weight: 0.20,
          colorVariant: 'warning',
          isPending: true,
          description: 'Assessing queue durability vs latency tradeoffs.',
        },
      ],
    },
    coverage: {
      totalPlanned: 8,
      totalEvaluated: 6,
      coveragePercent: 75,
      domains: [
        { name: 'APIs & Contracts', weight: 0.25, score: 3.4, questionsCount: 2, status: 'pending' },
        { name: 'Databases & Indexing', weight: 0.25, score: 3.6, questionsCount: 2, status: 'pending' },
        { name: 'Concurrency & Locking', weight: 0.25, score: 3.2, questionsCount: 2, status: 'pending' },
        { name: 'Project Trade-offs & Triage', weight: 0.25, score: 3.5, questionsCount: 2, status: 'pending' },
      ],
    },
    questionQuality: {
      roleRelevance: 3.8,
      levelFit: 3.9,
      clarity: 3.9,
      assessability: 3.7,
      topicCoveragePercent: 91,
      totalPromptsEvaluated: 8,
      recommendations: [
        'Calibration underway. Background worker evaluation job active.',
      ],
      rubricMetrics: [
        { dimension: 'Role Relevance', score: 3.8, description: 'Evaluation in progress' },
        { dimension: 'Level Fit', score: 3.9, description: 'Evaluation in progress' },
        { dimension: 'Clarity', score: 3.9, description: 'Evaluation in progress' },
        { dimension: 'Assessability', score: 3.7, description: 'Evaluation in progress' },
      ],
    },
    turns: [],
  },

  'ses_demo_reviewed_03': {
    id: 'ses_demo_reviewed_03',
    sessionId: 'ses_demo_reviewed_03',
    status: 'human_reviewed',
    reviewer: {
      name: 'Dr. Vikram Sharma',
      role: 'Staff Evaluator & Panel Chair',
      reviewedAt: '2026-09-27T16:20:00.000Z',
    },
    releasedAt: '2026-09-27T16:25:00.000Z',
    revision: 2,
    candidate: {
      id: 'usr_candidate_03',
      displayName: 'Devon Lee',
      email: 'devon.lee@example.com',
      avatarUrl: null,
      domain: 'computer_science',
      experienceLevel: 'senior',
      targetRole: 'Backend Systems Architect',
    },
    interview: {
      startedAt: '2026-09-26T11:00:00.000Z',
      completedAt: '2026-09-26T11:45:00.000Z',
      durationMinutes: 45,
      mode: 'Staff Architectural Boardroom',
      totalTurns: 8,
      answeredCount: 8,
    },
    scores: {
      composite: 3.7,
      max: 4.0,
      percentile: 96,
      criteria: [
        {
          id: 'correctness',
          label: 'Technical Correctness',
          score: 3.8,
          max: 4.0,
          weight: 0.35,
          colorVariant: 'accent',
          description: 'Verified by Staff Evaluator. Promoted from 3.5 following deeper analysis of distributed lock lease discussion.',
        },
        {
          id: 'reasoning',
          label: 'Architectural Reasoning',
          score: 3.9,
          max: 4.0,
          weight: 0.25,
          colorVariant: 'primary',
          description: 'Strong justification of partitioned write paths under Raft consensus.',
        },
        {
          id: 'relevance',
          label: 'Direct Relevance',
          score: 3.7,
          max: 4.0,
          weight: 0.20,
          colorVariant: 'success',
          description: 'Addresses all prompt constraints accurately.',
        },
        {
          id: 'tradeoffs',
          label: 'Trade-offs & Application',
          score: 3.5,
          max: 4.0,
          weight: 0.20,
          colorVariant: 'warning',
          description: 'Sound operational triage and telemetry trade-offs.',
        },
      ],
    },
    coverage: {
      totalPlanned: 8,
      totalEvaluated: 8,
      coveragePercent: 100,
      domains: [
        { name: 'Distributed Systems', weight: 0.30, score: 3.9, questionsCount: 3, status: 'mastered' },
        { name: 'Database Architecture', weight: 0.30, score: 3.8, questionsCount: 3, status: 'mastered' },
        { name: 'Contract Evolution', weight: 0.20, score: 3.6, questionsCount: 1, status: 'proficient' },
        { name: 'Operational Triage', weight: 0.20, score: 3.5, questionsCount: 1, status: 'proficient' },
      ],
    },
    questionQuality: {
      roleRelevance: 4.0,
      levelFit: 3.9,
      clarity: 4.0,
      assessability: 3.9,
      topicCoveragePercent: 98,
      totalPromptsEvaluated: 8,
      recommendations: [
        'Superb senior evaluation calibration. Question #3 provided deep discrimination for staff leveling.',
      ],
      rubricMetrics: [
        { dimension: 'Role Relevance', score: 4.0, description: 'Directly mirrors Staff Systems Architect role.' },
        { dimension: 'Level Fit', score: 3.9, description: 'Rigorous level testing with zero trivial syntax prompts.' },
        { dimension: 'Clarity', score: 4.0, description: 'Exemplary problem framing with explicit load profiles.' },
        { dimension: 'Assessability', score: 3.9, description: 'Calibrated rubrics with clear evidence links.' },
      ],
    },
    turns: [
      {
        turnPosition: 1,
        questionId: 'arch-intro',
        stage: 'icebreaker',
        panelRole: 'chair',
        panelName: 'Dr. Aris Thorne (Panel Chair)',
        prompt: 'Describe a high-throughput backend architecture you spearheaded. What were the bottleneck constraints and your primary interventions?',
        candidateAnswer: 'At my previous role, our payment ingest service processed 14,000 TPS during flash sales. The primary bottleneck was PostgreSQL row lock contention on account balances. I redesigned the balance updates into an append-only event log with partition key hashing and asynchronous materialized balance rollup workers.',
        score: 3.9,
        maxScore: 4.0,
        source: 'Staff Evaluator - Certified',
        evidence: {
          excerpt: 'redesigned the balance updates into an append-only event log with partition key hashing and asynchronous materialized balance rollup workers',
          criterion: 'Architectural Innovation & High-Throughput Scaling',
          explanation: 'Demonstrated mastery of CQRS and ledger-style balance isolation to eliminate synchronous write bottlenecks.',
          missingPoints: ['Could have discussed snapshotting frequency for materialized balance recalculation.'],
        },
        eligibleForRetry: false,
      },
    ],
  },
};

/**
 * Replay Transcripts with boardroom dialogue turns
 */
export const MOCK_REPLAYS = {
  'ses_demo_backend_01': {
    sessionId: 'ses_demo_backend_01',
    sessionTitle: 'Alex Chen — Backend Developer Boardroom Simulation',
    date: '2026-09-27',
    duration: '33 mins',
    candidate: {
      name: 'Alex Chen',
      role: 'Backend Developer',
      level: 'Junior',
    },
    panelists: [
      { id: 'chair', name: 'Dr. Aris Thorne', role: 'Panel Chair', affiliation: 'Staff Director of Engineering' },
      { id: 'specialist', name: 'Elena Rostova', role: 'Technical Specialist', affiliation: 'Principal Systems Architect' },
      { id: 'evaluator', name: 'Marcus Vance', role: 'Project Evaluator', affiliation: 'Head of Engineering Operations' },
    ],
    turns: [
      {
        id: 'turn-1',
        position: 1,
        stage: 'icebreaker',
        speakerRole: 'chair',
        speakerName: 'Dr. Aris Thorne',
        speakerTitle: 'Panel Chair',
        timestamp: '00:01:15',
        question: 'Describe a small backend project you built. What did it do, and which part did you personally implement?',
        answer: 'I developed an internal book reservation API using Node.js, Express, and PostgreSQL. I implemented user authentication with JWT, designed the database schema with foreign key constraints, and wrote the reservation endpoints with transaction boundaries so multiple users could not hold the last book simultaneously.',
        score: 3.7,
        topic: 'project_tradeoffs',
        constraint: null,
      },
      {
        id: 'turn-2',
        position: 2,
        stage: 'technical',
        speakerRole: 'specialist',
        speakerName: 'Elena Rostova',
        speakerTitle: 'Technical Specialist',
        timestamp: '00:04:40',
        question: 'You are adding POST /tasks. What would you validate before saving a task, and what response would you send for invalid input?',
        answer: 'First, I validate the payload format: ensure title is a non-empty string under 255 characters, priority is an enum [LOW, MEDIUM, HIGH], and dueDate is an ISO-8601 string in the future. For validation failures, I return HTTP 422 Unprocessable Entity with a structured JSON body listing field-level error messages (field, rule, message). If the request is malformed JSON, I return HTTP 400 Bad Request.',
        score: 3.8,
        topic: 'apis',
        constraint: null,
      },
      {
        id: 'turn-3',
        position: 3,
        stage: 'technical',
        speakerRole: 'specialist',
        speakerName: 'Elena Rostova',
        speakerTitle: 'Technical Specialist',
        timestamp: '00:09:20',
        question: 'Two users try to register the same email almost simultaneously. Why is checking whether the email exists before inserting insufficient, and what would you add?',
        answer: 'A SELECT query followed by an INSERT is vulnerable to a Time-of-Check to Time-of-Use (TOCTOU) race condition. Both concurrent requests can execute SELECT at the same instant, see 0 rows, and both proceed to INSERT. To guarantee uniqueness, I must enforce a database-level UNIQUE constraint on the email column. Then, in the application layer, catch the PostgreSQL unique violation error code (23505) and return a friendly 409 Conflict.',
        score: 3.9,
        topic: 'databases',
        constraint: null,
      },
      {
        id: 'turn-4',
        position: 4,
        stage: 'technical',
        speakerRole: 'specialist',
        speakerName: 'Elena Rostova',
        speakerTitle: 'Technical Specialist',
        timestamp: '00:14:05',
        question: 'An item has one unit left. Two requests both read the stock as one and both place an order. Explain a database approach that prevents selling two units.',
        answer: 'We can run the order placement inside an explicit database transaction and use SELECT stock FROM inventory WHERE item_id = 123 FOR UPDATE. This takes an exclusive row-level lock. The second transaction will block until the first commits and reduces stock to zero. Alternatively, we could do UPDATE inventory SET stock = stock - 1 WHERE item_id = 123 AND stock >= 1, checking the affected rows count.',
        score: 3.4,
        topic: 'concurrency',
        constraint: null,
      },
      {
        id: 'turn-5',
        position: 5,
        stage: 'technical',
        speakerRole: 'specialist',
        speakerName: 'Elena Rostova',
        speakerTitle: 'Technical Specialist',
        timestamp: '00:18:50',
        question: 'How does your stock reservation handle network timeouts when a third-party payment gateway is slow to respond?',
        constraint: {
          change: 'Two identical requests now arrive simultaneously from the same client due to an aggressive mobile retry timeout.',
          followUp: 'Explain how your architecture prevents double-allocation while ensuring the client receives the authoritative order state on retry.',
        },
        answer: 'If payment times out, we should probably rollback the order or wait for webhook. If two identical requests arrive, we can check if the user has an existing order in the table and reject the second one.',
        score: 2.3,
        topic: 'concurrency',
        eligibleForRetry: true,
        targetSkill: 'Idempotent Payment Handling & Retry Deduplication',
      },
      {
        id: 'turn-6',
        position: 6,
        stage: 'techno_managerial',
        speakerRole: 'evaluator',
        speakerName: 'Marcus Vance',
        speakerTitle: 'Project Evaluator',
        timestamp: '00:23:15',
        question: 'Your team has one day left. Search filters and reliable task saving are both unfinished. How would you choose scope and communicate the decision?',
        answer: 'Data persistence and reliability always take precedence over convenience features. If task saving fails, the product loses user data, which destroys user trust. Search filters can be substituted temporarily with basic sorting or in-memory list rendering. I would immediately message the engineering manager and product lead explaining: 1) why reliable task saving is critical path, 2) proposing to ship basic saving first, and 3) deferring search filters to the next sprint.',
        score: 3.8,
        topic: 'project_tradeoffs',
        constraint: null,
      },
      {
        id: 'turn-7',
        position: 7,
        stage: 'techno_managerial',
        speakerRole: 'evaluator',
        speakerName: 'Marcus Vance',
        speakerTitle: 'Project Evaluator',
        timestamp: '00:27:40',
        question: 'A frontend teammate expects dueDate but your API returns deadline. How would you resolve this mismatch and prevent similar integration surprises?',
        answer: 'In the immediate term, I would update the API serializer to return both dueDate and deadline (aliasing the field) so neither the existing frontend nor new builds break. Then we can deprecate deadline. To prevent this, I would establish OpenAPI/Swagger contracts stored in a shared repository with automated schema validation in our CI pipeline.',
        score: 3.7,
        topic: 'apis',
        constraint: null,
      },
      {
        id: 'turn-8',
        position: 8,
        stage: 'reflection',
        speakerRole: 'chair',
        speakerName: 'Dr. Aris Thorne',
        speakerTitle: 'Panel Chair',
        timestamp: '00:31:00',
        question: 'Which answer today would you improve with another ten minutes, and how would you check whether your revised approach is correct?',
        answer: 'I would improve my response on question #5 regarding third-party payment timeouts and retries. I should have explained Idempotency Keys stored with a unique constraint in a Redis or Postgres table to guarantee that multiple mobile retry requests do not double charge. To verify correctness, I would write an automated integration test using Promise.all() to fire 5 identical concurrent requests with the same idempotency key and verify that only one charge is executed while all 5 receive the same order ID.',
        score: 3.9,
        topic: 'project_tradeoffs',
        constraint: null,
      },
    ],
  },
};

/**
 * Review Assignments for Expert Dashboard (/expert)
 */
export const MOCK_REVIEW_ASSIGNMENTS = [
  {
    id: 'asg_01',
    sessionId: 'ses_demo_backend_01',
    candidate: {
      id: 'usr_candidate_01',
      name: 'Alex Chen',
      email: 'alex.chen@example.com',
      avatarUrl: null,
      role: 'Backend Developer',
      level: 'Junior',
    },
    interviewDate: '2026-09-27',
    interviewDuration: '33 mins',
    status: 'draft', // 'draft' | 'reviewed' | 'pending'
    statusLabel: 'AI Draft Ready',
    aiScore: 3.4,
    reviewedScore: null,
    flaggedTurnsCount: 1,
    flaggedReason: 'Turn #5 low confidence on distributed retry handling (score 2.3). Requires evaluator verification.',
    assignedEvaluator: 'Dr. Vikram Sharma',
  },
  {
    id: 'asg_02',
    sessionId: 'ses_demo_pending_02',
    candidate: {
      id: 'usr_candidate_02',
      name: 'Maya Patel',
      email: 'maya.patel@example.com',
      avatarUrl: null,
      role: 'Full Stack Engineer',
      level: 'Mid-Level',
    },
    interviewDate: '2026-09-27',
    interviewDuration: '42 mins',
    status: 'pending',
    statusLabel: 'Pending AI Grading',
    aiScore: null,
    reviewedScore: null,
    flaggedTurnsCount: 0,
    flaggedReason: 'Asynchronous calibration grading queue #3 in progress.',
    assignedEvaluator: 'Dr. Vikram Sharma',
  },
  {
    id: 'asg_03',
    sessionId: 'ses_demo_reviewed_03',
    candidate: {
      id: 'usr_candidate_03',
      name: 'Devon Lee',
      email: 'devon.lee@example.com',
      avatarUrl: null,
      role: 'Backend Systems Architect',
      level: 'Senior',
    },
    interviewDate: '2026-09-26',
    interviewDuration: '45 mins',
    status: 'reviewed',
    statusLabel: 'Certified Human Reviewed',
    aiScore: 3.5,
    reviewedScore: 3.7,
    flaggedTurnsCount: 0,
    flaggedReason: 'Authoritative evaluation signed off by Staff Evaluator.',
    assignedEvaluator: 'Dr. Vikram Sharma',
    releasedAt: '2026-09-27T16:25:00.000Z',
  },
];

/**
 * Question Lab Presets & Evaluator Sandbox Data
 */
export const QUESTION_LAB_PRESETS = [
  {
    id: 'preset-concurrency',
    title: 'Distributed Payment Retry Race',
    role: 'Backend Developer',
    level: 'Junior-to-Mid',
    topic: 'concurrency',
    question: 'How do you handle an aggressive mobile client that retries an order payment request 3 times within 2 seconds because of a transient Wi-Fi timeout?',
    sampleAnswer: 'Require client to send an Idempotency-Key UUID header. Store the key in Redis or Postgres with a UNIQUE constraint and state PENDING. Reject simultaneous duplicates with 409 or return the cached final response.',
  },
  {
    id: 'preset-api',
    title: 'API Versioning & Breaking Changes',
    role: 'Backend Developer',
    level: 'Junior',
    topic: 'apis',
    question: 'You must deprecate a required userId parameter in POST /orders and replace it with bearer token claims without breaking existing legacy mobile clients. How do you roll this out?',
    sampleAnswer: 'Make userId optional in the request schema. If provided, verify it matches the token claims. If omitted, extract userId directly from the verified JWT. Log deprecation warnings and telemetry headers before sunsetting.',
  },
  {
    id: 'preset-database',
    title: 'Database Locking Under High Contention',
    role: 'Backend Systems Architect',
    level: 'Senior',
    topic: 'databases',
    question: 'When multiple microservices book seats for an arena concert simultaneously, how do you prevent phantom reads and double-booking without creating catastrophic database lock queuing?',
    sampleAnswer: 'Partition seat availability into discrete blocks with short distributed Redis leases (TTL 5 mins) before taking Postgres locks. Use optimistic locking with row versions or conditional updates for final checkout.',
  },
];
